#!/usr/bin/env node
/**
 * Computes the sha256 hashes of every inline <script> in the built output and
 * writes the Content-Security-Policy into netlify.toml.
 *
 *   node scripts/build-csp.mjs        rewrite netlify.toml with current hashes
 *   node scripts/build-csp.mjs --check  fail if netlify.toml is out of date
 *
 * Hashes are what let script-src drop 'unsafe-inline'. They are also a policy
 * that breaks silently the moment an inline script changes, which is worse than
 * no policy — so the check is part of the feature, not an extra. `npm run check`
 * runs it, and it fails loudly on drift.
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist')
const tomlPath = join(root, 'netlify.toml')

const START = '# --- csp:begin (generated by scripts/build-csp.mjs) ---'
const END = '# --- csp:end ---'

function htmlFiles(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) out.push(...htmlFiles(full))
    else if (name.endsWith('.html')) out.push(full)
  }
  return out
}

const hashes = new Set()
for (const file of htmlFiles(dist)) {
  const html = readFileSync(file, 'utf8')
  // Inline scripts only: anything with src is covered by 'self'.
  for (const [, attrs, body] of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
    if (/\ssrc=/.test(attrs)) continue
    if (!body) continue
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
  }
}

const sorted = [...hashes].sort()

/*
  style-src keeps 'unsafe-inline'. Astro emits scoped component styles and the
  whole stylesheet is inlined for first paint, so the hash set would churn on
  every style edit. Scripts are the ones worth pinning.
*/
const policy = [
  "default-src 'self'",
  `script-src 'self' ${sorted.join(' ')}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
].join('; ')

const block = [
  START,
  '# Report-only for now: it produces the evidence for enforcing later without',
  '# risking a live break. Regenerate with `node scripts/build-csp.mjs`.',
  '[[headers]]',
  '  for = "/*"',
  '  [headers.values]',
  `    Content-Security-Policy-Report-Only = "${policy}"`,
  '    Cross-Origin-Opener-Policy = "same-origin"',
  END,
].join('\n')

const toml = readFileSync(tomlPath, 'utf8')
const existing = toml.includes(START)
  ? toml.slice(toml.indexOf(START), toml.indexOf(END) + END.length)
  : null

if (process.argv.includes('--check')) {
  if (existing === block) {
    console.log(`\n  CSP is current: ${sorted.length} inline script hash(es) pinned\n`)
    process.exit(0)
  }
  console.error(
    '\n  netlify.toml CSP is out of date with the built output.' +
      '\n  An inline script changed, so its hash no longer matches and the policy' +
      '\n  would silently stop covering it.' +
      '\n\n  Fix: npm run build && node scripts/build-csp.mjs\n'
  )
  process.exit(1)
}

writeFileSync(tomlPath, existing ? toml.replace(existing, block) : `${toml.trimEnd()}\n\n${block}\n`)
console.log(`\n  wrote CSP to netlify.toml with ${sorted.length} inline script hash(es)\n`)
